

services:
  api-gateway:
    build: ./api-gateway
    container_name: api_gateway
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - JWT_SECRET=your_jwt_secret_key
      - PRODUCT_SERVICE_URL=http://product-service:3001
      - ORDER_SERVICE_URL=http://order-service:3002
      - AUTH_SERVICE_URL=http://auth-service:3003
    depends_on:
      - product-service
      - order-service
      - auth-service

  product-service:
    build: ./product-service
    container_name: product_service
    ports:
      - "3001:3001"
    env_file:
      - ./product-service/.env

  order-service:
    build: ./order-service
    container_name: order_service
    ports:
      - "3002:3002"
    env_file:
      - ./order-service/.env

  auth-service:
    build: ./auth-service
    container_name: auth_service
    ports:
      - "3003:3003"
    env_file:
      - ./auth-service/.env